### ISSUE TITLE
easy-fix bugs in step 7. 

### ISSUE THREAD

**Issue by ubbu36** [CWorthy-ocean/C-Star_ARCHIVE#14]
step 7 Make_atm_forcing_BGC has several problems.

1. In correction_on_FRCtime.m, you have to hard-code the year. This seems like a very easy fix for this function to pull that info from make_frcBGC.m

2. the code adds 'cycle_length' as an attribute in the netcdf file, which can cause a lot of issues when running, and I suggest we just remove this attribute unless there's a reason for it I'm unaware of.

3. For the MARBL specific step 7, the code needs to add the variable pco2_air_alt, should be easy just to copy the pco2_air as a default.

**Comment by dafyddstephenson** [comment]
Hi @ubbu36 do you know if this got addressed? If it is still a problem could you raise a new issue over on the relocated MATLAB setup tools repo? https://github.com/CWorthy-ocean/matlab_setup_tools . I will close it here for now.
