### ISSUE TITLE
bry_time is hardcoded in step 9b for MARBL setup (easy-fix)

### ISSUE THREAD

**Issue by ubbu36** [CWorthy-ocean/C-Star_ARCHIVE#15]
bry_time is hardcoded in correction_on_BRYtime.m 

This is not a good practice and should be very easy to fix

**Comment by dafyddstephenson** [comment]
Hi @ubbu36 do you know if this got addressed? If it is still a problem could you raise a new issue over on the relocated MATLAB setup tools repo? https://github.com/CWorthy-ocean/matlab_setup_tools . I will close it here for now.
