### ISSUE TITLE
ERROR: In repo "roms": reference "27a31e29f1126a6fcf2675a032655acde4487d6e"

### ISSUE THREAD

**Issue by saadqayum** [CWorthy-ocean/C-Star_ARCHIVE#25]
Hi guys when i am trying to setup this on my mac m3 pro, i get this error

`**ERROR: In repo "roms": reference "27a31e29f1126a6fcf2675a032655acde4487d6e" does not appear to be a valid tag, branch or hash! Please verify the reference name (e.g. spelling), is available from: https://github.com/dafyddstephenson/ucla-roms.git**`

Steps i followed:

- installed miniconda
- cloned the repo
- in setup_cstart ran command: ./setup_cstar osx_x64_gnu

and at the end of above command i got this error

- although after this error i ran `conda active /setupctarenvlocation`

- and when i did run the command: ` cstar_get_blueprint roms_marbl_example`

and got this error:
`**rsync -a /Users/mac/Desktop/C-Star/setup_cstar/externals/ucla-roms//src/*.F /Users/mac/Desktop/C-Star/setup_cstar/externals/ucla-roms//src/*.h  Compile
make show_tag
sed: 1: "Compile/add_git_hash.F": invalid command code C
make[1]: *** [show_tag] Error 1
make: *** [all] Error 2**`

**Comment by TomNicholas** [comment]
Hi @saadqayum ! Thank you for your interest in C-Star! I'm curious where you work - what's your interest in this project?

> i get this error

We have not actually released version 1 of C-Star yet, so until then all code in this repository should be treated as a work-in-progress. If you star or follow the repository you should get a github notification once we release, and then it will be ready to try out :)

**Comment by dafyddstephenson** [comment]
Hi @saadqayum , I have a feeling I know where this error comes from: ROMS has recently had its commit history re-written, so the script seems to be trying to check out ROMS at a commit hash that is no longer valid. Unfortunately this is quite bad timing as our entire repository is _also_ getting overhauled currently, but I will keep this issue open and try to set things straight as soon as possible - it'd be nice to see it running on an M3 machine! Thanks for your interest ☺️

**Comment by dafyddstephenson** [comment]
Hi @saadqayum , as an update, I've transferred the relevant code to its own repository and fixed up any issues, so it's now working for me: https://github.com/CWorthy-ocean/roms_marbl_setup_assistant

Could you give this a try from scratch and then raise an issue there if you encounter any problems? Thanks!
